Option Strict Off
Option Explicit On
Module Bas_ExportVisualBasicLookupForm
	Private Const ModuleName As String = "Bas_ExportVisualBasicLookupForm"
	
	Public Sub ExportVBLookupForm(ByVal ConnectionString As String, ByVal Rs As ADODB.Recordset, ByVal VBForm As String)
		
		Dim WriteTs As Scripting.TextStream
		
		Dim Fieldidx As Short
		Dim lblfield As String
		Dim txtfield As String
		
		Dim txtrs As String
		
		Dim FormHeader As String
		Dim FormContent As String
		Dim Line As String
		
		WriteTs = Fso.OpenTextFile(VBForm, Scripting.IOMode.ForWriting, True)
		
		WriteTs.WriteLine("VERSION 5.00")
		WriteTs.WriteLine("Object = ""{831FDD16-0C5C-11D2-A9FC-0000F8754DA1}#2.0#0""; ""MSCOMCTL.OCX""")
		WriteTs.WriteLine("Object = ""{F9043C88-F6F2-101A-A3C9-08002B2F49FB}#1.2#0""; ""comdlg32.ocx""")
		WriteTs.WriteLine("Begin VB.Form Form1 ")
		WriteTs.WriteLine("   Caption         =   ""Form1""")
		WriteTs.WriteLine("   ClientHeight    =   7920")
		WriteTs.WriteLine("   ClientLeft      =   60")
		WriteTs.WriteLine("   ClientTop       =   345")
		WriteTs.WriteLine("   ClientWidth     =   6930")
		WriteTs.WriteLine("   LinkTopic       =   ""Form1""")
		WriteTs.WriteLine("   ScaleHeight     =   7920")
		WriteTs.WriteLine("   ScaleWidth      =   6930")
		WriteTs.WriteLine("   StartUpPosition =   2  'CenterScreen")
		WriteTs.WriteLine("   Begin MSComDlg.CommonDialog CommonDialog1 ")
		WriteTs.WriteLine("      Left            =   120")
		WriteTs.WriteLine("      Top             =   7320")
		WriteTs.WriteLine("      _ExtentX        =   847")
		WriteTs.WriteLine("      _ExtentY        =   847")
		WriteTs.WriteLine("      _Version        =   393216")
		WriteTs.WriteLine("   End")
		WriteTs.WriteLine("   Begin MSComctlLib.ListView ListView1 ")
		WriteTs.WriteLine("      Height          =   5055")
		WriteTs.WriteLine("      Left            =   120")
		WriteTs.WriteLine("      TabIndex        =   0")
		WriteTs.WriteLine("      Top             =   120")
		WriteTs.WriteLine("      Width           =   6615")
		WriteTs.WriteLine("      _ExtentX        =   11668")
		WriteTs.WriteLine("      _ExtentY        =   8916")
		WriteTs.WriteLine("      View            =   3")
		WriteTs.WriteLine("      LabelEdit       =   1")
		WriteTs.WriteLine("      MultiSelect     =   -1  'True")
		WriteTs.WriteLine("      LabelWrap       =   0   'False")
		WriteTs.WriteLine("      HideSelection   =   0   'False")
		WriteTs.WriteLine("      AllowReorder    =   -1  'True")
		WriteTs.WriteLine("      GridLines       =   -1  'True")
		WriteTs.WriteLine("      _Version        =   393217")
		WriteTs.WriteLine("      ForeColor       =   -2147483640")
		WriteTs.WriteLine("      BackColor       =   -2147483643")
		WriteTs.WriteLine("      BorderStyle     =   1")
		WriteTs.WriteLine("      Appearance      =   1")
		WriteTs.WriteLine("      NumItems        =   " & Rs.Fields.Count)
		
		For Fieldidx = 0 To Rs.Fields.Count - 1
			
			WriteTs.WriteLine("      BeginProperty ColumnHeader(" & CStr(Fieldidx + 1) & ") {BDD1F052-858B-11D1-B16A-00C0F0283628} ")
			WriteTs.WriteLine("         Text            =   """ & Rs.Fields(Fieldidx).Name & """")
			WriteTs.WriteLine("         Object.Width           =   2540")
			WriteTs.WriteLine("      EndProperty")
			
		Next 
		
		WriteTs.WriteLine("   End")
		WriteTs.WriteLine("   Begin VB.Menu MnuPopUpMenu ")
		WriteTs.WriteLine("      Caption         =   ""PopUp Menu""")
		WriteTs.WriteLine("      Visible         =   0   'False")
		WriteTs.WriteLine("      Begin VB.Menu MnuFont ")
		WriteTs.WriteLine("         Caption         =   ""Font""")
		WriteTs.WriteLine("      End")
		WriteTs.WriteLine("      Begin VB.Menu MnuGrid ")
		WriteTs.WriteLine("         Caption         =   ""Grid""")
		WriteTs.WriteLine("      End")
		WriteTs.WriteLine("   End")
		WriteTs.WriteLine("End")
		WriteTs.WriteLine("Attribute VB_Name = ""Form1""")
		WriteTs.WriteLine("Attribute VB_GlobalNameSpace = False")
		WriteTs.WriteLine("Attribute VB_Creatable = False")
		WriteTs.WriteLine("Attribute VB_PredeclaredId = True")
		WriteTs.WriteLine("Attribute VB_Exposed = False")
		WriteTs.WriteLine("''Code Ready " & VB6.Format(Now, "yyyy/MM/dd HH:mm:ss"))
		WriteTs.WriteBlankLines((2))
		WriteTs.WriteLine("'Please add the following component to run this form")
		WriteTs.WriteLine("'1. Microsoft Common Dialog Control 6.0, comdlg32.OCX")
		WriteTs.WriteLine("'2. Microsoft Windows Common Control 6.0 (SP6), MSCOMCTL.OCX")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Dim Cn As New ADODB.Connection")
		WriteTs.WriteLine("Dim Rs As New ADODB.Recordset")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub Form_Load()")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("        Dim connstr As String")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("        Dim SQL As String")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("        connstr = """ & ConnectionString & """")
		WriteTs.WriteLine("        Cn.Open connstr")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("        SQL = """ & Rs.Source & """")
		WriteTs.WriteLine("        Rs.Open SQL, Cn, 1, 3")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("        Call CreateListView(Rs)")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub Form_Unload(Cancel As Integer)")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    Rs.Close")
		WriteTs.WriteLine("    Cn.Close")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    Set Rs = Nothing")
		WriteTs.WriteLine("    Set Cn = Nothing")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub CreateListView(ByVal Rs As ADODB.Recordset)")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("   Dim NewItem As ListItem")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    On Error GoTo ErrorHandler")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    MousePointer = vbHourglass")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    With ListView1")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("        .ListItems.Clear")
		WriteTs.WriteLine("        Do Until Rs.EOF")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("            Set NewItem = .ListItems.Add(Rs.AbsolutePosition, , Rs(0))")
		
		For Fieldidx = 1 To Rs.Fields.Count - 1
			WriteTs.WriteLine("            If IsNull(Rs(" & CStr(Fieldidx) & ")) = False Then")
			WriteTs.WriteLine("                NewItem.SubItems(" & CStr(Fieldidx) & ") = cstr(Rs(" & CStr(Fieldidx) & "))")
			WriteTs.WriteLine("            End If")
		Next 
		WriteTs.WriteLine("            Rs.MoveNext")
		WriteTs.WriteLine("        Loop")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("    End With")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    MousePointer = vbDefault")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    Exit Sub")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("ErrorHandler:")
		WriteTs.WriteLine("    MousePointer = vbDefault")
		WriteTs.WriteLine("    MsgBox Err.Description, vbCritical")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub ListView1_ColumnClick(ByVal ColumnHeader As MSComctlLib.ColumnHeader)")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    With ListView1")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("        If .SortKey = ColumnHeader.Index - 1 Then")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("            If .SortOrder = lvwAscending Then")
		WriteTs.WriteLine("                    .SortOrder = lvwDescending")
		WriteTs.WriteLine("            Else")
		WriteTs.WriteLine("                    .SortOrder = lvwAscending")
		WriteTs.WriteLine("            End If")
		WriteTs.WriteLine("                        ")
		WriteTs.WriteLine("        Else")
		WriteTs.WriteLine("            ")
		WriteTs.WriteLine("            .SortKey = ColumnHeader.Index - 1")
		WriteTs.WriteLine("            .SortOrder = lvwAscending")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("        End If")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("        .Sorted = True")
		WriteTs.WriteLine("        ")
		WriteTs.WriteLine("    End With")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub Form_Resize()")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    On Error Resume Next")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    With ListView1")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("        .Width = Me.Width - 500")
		WriteTs.WriteLine("        .Height = Me.Height - 500")
		WriteTs.WriteLine("                ")
		WriteTs.WriteLine("    End With")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub ListView1_MouseDown(Button As Integer, Shift As Integer, x As Single, y As Single)")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    Select Case Button")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    Case 2")
		WriteTs.WriteLine("        PopUpMenu MnuPopUpMenu")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    End Select")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub MnuFont_Click()")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    Call OpenFontDialog(CommonDialog1)")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    With ListView1")
		WriteTs.WriteLine("        .Font.Name = CommonDialog1.FontName")
		WriteTs.WriteLine("        .Font.Size = CommonDialog1.FontSize")
		WriteTs.WriteLine("        .Font.Underline = CommonDialog1.FontUnderline")
		WriteTs.WriteLine("        .Font.Italic = CommonDialog1.FontItalic")
		WriteTs.WriteLine("        .ForeColor = CommonDialog1.Color")
		WriteTs.WriteLine("    End With")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Sub MnuGrid_Click()")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("    ListView1.GridLines = Not ListView1.GridLines")
		WriteTs.WriteLine("    MnuGrid.Checked = ListView1.GridLines")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End Sub")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("Private Function OpenFontDialog(ByRef CDL As CommonDialog) As CommonDialog")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("'You may remove this function by adding the Bas_CommDialog.bas")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("On Error Resume Next")
		WriteTs.WriteLine("With CDL")
		WriteTs.WriteLine("    .Flags = 0   'Required before setting FontName")
		WriteTs.WriteLine("    .FontName = ""MS Sans Serif""")
		WriteTs.WriteLine("     .Flags = cdlCFBoth + cdlCFEffects")
		WriteTs.WriteLine("    .CancelError = True")
		WriteTs.WriteLine("    .ShowFont")
		WriteTs.WriteLine("    If Not Err.Number = 0 Then")
		WriteTs.WriteLine("        Exit Function")
		WriteTs.WriteLine("    End If")
		WriteTs.WriteLine("    Set OpenFontDialog = CDL")
		WriteTs.WriteLine("    ")
		WriteTs.WriteLine("End With")
		WriteTs.WriteLine("")
		WriteTs.WriteLine("End Function")
		
		
		WriteTs.Close()
		
		
	End Sub
End Module